# Generated by Django 4.1.3 on 2022-11-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_albumpic',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
