# Generated by Django 4.1.3 on 2022-12-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_playlist_playlist2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_albumpic',
        ),
        migrations.AddField(
            model_name='music',
            name='music_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
