# Generated by Django 4.1.3 on 2022-11-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_music_music_albumpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_albumpic',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
