# Generated by Django 4.1.3 on 2022-12-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_playlist_delete_playlist2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.music', unique=True),
        ),
    ]
