# Generated by Django 4.1.3 on 2022-11-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_music_music_albumpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_albumpic',
        ),
    ]
