# Generated by Django 4.1.3 on 2022-12-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_playlist_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.music'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('user', 'music'), name='unique_user_playlist'),
        ),
    ]
